### ISSUE TITLE
question about ContinueConversation task

### ISSUE THREAD

**Issue by lizijian-buaa** [liyucheng09/LLMs_Memorize#24]
Hi. When reading the code, I think for the ContinueConversation task, u use all the conversion rounds to construct the input prompt, which includes the original GPT last-round reply. Is this a mis-implementation?
BTW, So glad to see such good work. Thx!

**Comment by liyucheng09** [comment]
Thanks for your interests on selective-context.

Actually we use the whole context except the last utterence, see [here](https://github.com/liyucheng09/Selective_Context/blob/main/context_manager.py#L504) for the details.

**Comment by lizijian-buaa** [comment]
thx for your so quick reply, but I think the "prompt = '\n'.join(lines[:-1])" is not used in the code. Should we set sections=[prompt , last_response] instead of [content, last_response].

**Comment by liyucheng09** [comment]
could you run a debug and check [here](https://github.com/liyucheng09/Selective_Context/blob/3074343653bbf3559a87a588667e843744bc6f2a/context_manager.py#L370). To see whether it's using the correct context?

**Comment by lizijian-buaa** [comment]
Oh, I see. Thx a lot.
